name: eventify
description: "Reminder of important days."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localization: 0.1.14

  #utils
  visibility_detector: ^0.4.0+2
  meta: any
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  camera: 0.10.5+9
  flutter_platform_alert: 0.4.0
  permission_handler: ^10.2.0
  url_launcher: ^6.1.11
  file_picker: ^5.3.3
  image_picker: 1.0.4
  intl: 0.18.1
  flutter_keyboard_visibility: ^5.4.1
  mask_text_input_formatter: 2.5.0
  fl_chart: ^0.68.0

  #dependency_injection
  injectable: ^2.3.2
  get_it: ^7.6.4

  #network
  dio: ^5.4.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  json_serializable: ^6.7.1

  #code_gen:
  freezed: ^2.4.2
  json_annotation: ^4.8.1


  #logger:
  talker_flutter: ^4.0.0
  talker_bloc_logger: ^4.0.0
  talker_dio_logger: ^4.0.0
  logger: ^2.0.1
  alice: ^0.3.3

  #database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #state_manager
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.3

  #code
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app_icons/
    - assets/fonts/
    - assets/icons/
    - assets/img/
    - assets/onboarding/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.otf
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica_light.otf
        - asset: assets/fonts/helvetica_regular.otf
        - asset: assets/fonts/helvetica_bold.otf
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
        - asset: assets/fonts/ProximaNova-Semibold.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Medium.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf